export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Chinese",
  "Japanese",
  "Korean",
  "Italian",
  "Russian",
  "Portuguese",
  "Arabic",
  "Hindi",
  "Bengali",
  "Punjabi",
  "Javanese",
  "Vietnamese",
  "Turkish",
  "Amharic",
];

export const LANGUAGE_TO_FLAG = {
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  chinese: "zh",
  japanese: "ja",
  korean: "ko",
  italian: "it",
  russian: "ru",
  portuguese: "pt",
  arabic: "ar",
  hindi: "hi",
  bengali: "bn",
  punjabi: "pa",
  javanese: "jv",
  vietnamese: "vi",
  turkish: "tr",
  amharic: "et",
};